export const CREATE_FLASHCARD = 'CREATE_FLASHCARD';
export const EDIT_FLASHCARD = 'EDIT_FLASHCARD';
export const DELETE_FLASHCARD = 'DELETE_FLASHCARD';
export const CREATE_SET = 'CREATE_SET';
export const ERROR = 'ERROR';
